-- capacity table (probably should be combined with global inventory table)
create table
  public.capacity (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    potion_capacity integer null default 50,
    ml_capacity integer null default 10000,
    constraint capacity_pkey primary key (id)
  ) tablespace pg_default;

-- global_inventory table
create table
  public.global_inventory (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    num_green_ml integer null default 0,
    gold integer null default 100,
    num_red_ml integer null default 0,
    num_blue_ml integer null,
    num_potions integer null default 0,
    num_dark_ml integer null default 0,
    constraint global_inventory_pkey primary key (id)
  ) tablespace pg_default;

-- customers table
create table
  public.customers (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    customer_name text null,
    character_class text null,
    level integer null default 0,
    constraint customers_pkey primary key (id)
  ) tablespace pg_default;

-- items table
create table
  public.items (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    red_qty integer null default 0,
    green_qty integer null default 0,
    blue_qty integer null default 0,
    dark_qty integer null default 0,
    sku text null,
    cost integer null,
    qty integer null default 0,
    constraint items_pkey primary key (id)
  ) tablespace pg_default;

-- carts table
create table
  public.carts (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    character_id bigint null,
    item_qty integer null default 0,
    item_id bigint not null,
    constraint carts_pkey primary key (id, item_id),
    constraint public_carts_character_id_fkey foreign key (character_id) references customers (id),
    constraint public_carts_item_id_fkey foreign key (item_id) references items (id)
  ) tablespace pg_default;

--   time table
create table
  public.time (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    day text null,
    hour integer null,
    constraint time_pkey primary key (id)
  ) tablespace pg_default;